<a href="https://colab.research.google.com/github/vanshdhar999/Pytorch-Intro/blob/main/Pytorch101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as th
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## This is a introduction to Pytorch for Machine Learning and Deep Learning. Youtube link: https://www.youtube.com/watch?v=V_xro1bcAuA&t=10326s

## Introduction to Tensors
Tensors are a way to store numeric data and multidimensional data.

In [ ]:
# scalar tensor
scalar = th.tensor(7)
# this is a scalar with 0 dimension

In [ ]:
#how to find the dimension of the tensor
scalar.ndim

0

In [ ]:
#get tensor item back as a python int
scalar.item()

7

In [ ]:
 #Vector in Tensor
 vector = th.tensor([1, 2])
 vector.ndim

1

In [ ]:
#Matrix
MATRIX = th.tensor([[1, 12, 3],
                    [1, 12,1]])
MATRIX.ndim

2

In [ ]:

#Tensor, any dimension, a general thumb of rule for remembering the dimension
# (a, b, c) a -> outer dimension
          # b and c  -> row x column
TENSOR = th.tensor([[[1, 2, 3],
                     [2, 3, 4],
                     [3, 4,5]]])
TENSOR.shape # gives the size of the tensor

torch.Size([1, 3, 3])

In [ ]:
# Examples of tensor
Tensor2 = th.tensor([[[1, 2],
                      [2, 3],
                       [3, 4]]])
Tensor2.size()

torch.Size([1, 3, 2])

## Random Tensors

In [ ]:
random_tensor = th.rand(1, 3, 4)
random_tensor

tensor([[[0.5552, 0.6000, 0.6080, 0.9710],
         [0.1481, 0.4665, 0.6118, 0.2092],
         [0.5722, 0.7549, 0.3792, 0.9263]]])

In [ ]:
# Images have tensors of shape (channels, height, width)
random_image_tensor = th.rand(3, 244, 244)
random_image_tensor

tensor([[[0.9837, 0.7580, 0.7884,  ..., 0.8971, 0.3273, 0.3252],
         [0.5587, 0.2173, 0.1329,  ..., 0.3857, 0.1611, 0.8899],
         [0.1921, 0.8905, 0.2670,  ..., 0.0939, 0.9866, 0.3077],
         ...,
         [0.5696, 0.6718, 0.8086,  ..., 0.9138, 0.1169, 0.4741],
         [0.8857, 0.9170, 0.8346,  ..., 0.2815, 0.0053, 0.3469],
         [0.3918, 0.5421, 0.7179,  ..., 0.8568, 0.2325, 0.5583]],

        [[0.4329, 0.7009, 0.1289,  ..., 0.1569, 0.3619, 0.4552],
         [0.6121, 0.7293, 0.0019,  ..., 0.2017, 0.5681, 0.9567],
         [0.2262, 0.3774, 0.2519,  ..., 0.8494, 0.1913, 0.8783],
         ...,
         [0.6469, 0.1018, 0.9212,  ..., 0.5591, 0.5820, 0.2248],
         [0.9526, 0.9462, 0.2297,  ..., 0.4059, 0.9477, 0.1950],
         [0.0606, 0.5762, 0.7568,  ..., 0.1004, 0.6527, 0.4593]],

        [[0.7933, 0.9572, 0.6305,  ..., 0.6507, 0.9010, 0.0829],
         [0.1178, 0.7197, 0.8575,  ..., 0.0085, 0.3633, 0.9746],
         [0.3088, 0.2477, 0.1636,  ..., 0.6170, 0.5393, 0.

In [ ]:
#Zeros and ones tensors
zero = th.zeros(3, 3)
ones = th.ones(3, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Tensors range and tensors like

In [ ]:
tensor_range = th.arange(start = 1, end = 11, step = 1)
tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
## If we want to create a tensor with the same dimension as the other tensor
tensor_like_range_zero = th.zeros_like(input=tensor_range)
tensor_like_range_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensors datatype
Default datatype is float32
We can change the dtype with
`dtype = data_type`

In [ ]:
float_32_tensor = th.tensor([1, 2, 3],
                            dtype=None,
                            device='cpu',
                            requires_grad = False)

##Tensor Operations
Addition
Multiplication(element-wise and normal)
Subtraction
Division

In [ ]:
# Addition and Subtraction is done using +, -
%%time
tensor_1 = th.tensor([1,2,3])
tensor_2 = th.tensor([1, 2, 3])
tensor_1 * tensor_2 # Element Wise multiplication

CPU times: user 315 µs, sys: 0 ns, total: 315 µs
Wall time: 329 µs


tensor([1, 4, 9])

In [ ]:
# Matrix multiplication is done using matmul
print(f"tensor_1 dim {tensor_1.ndim} tensor_2 dim {tensor_2.ndim}")
th.matmul(tensor_1, tensor_2)

tensor_A = th.rand(3, 2)
tensor_B = th.rand(2, 3)

result = th.matmul(tensor_A, tensor_B)
result

tensor_1 dim 1 tensor_2 dim 1


tensor([[0.3063, 0.7043, 0.3284],
        [0.4867, 1.0711, 0.5751],
        [0.4413, 0.9677, 0.5256]])

##Using transpose we can change the dimensions of the tensor

In [ ]:
## Transpose is used as tensor.T



## Tensor Aggregation
We can find the min, max and the mean of the tensor

In [ ]:
tensor_1= th.tensor([[2, 3],
                  [3, 2]], dtype=th.float32)
tensor_1.type(th.float32)
print(f"type {tensor_1.dtype}")

type torch.float32


In [ ]:
## Min and Max of tensor
tensor_1 = th.tensor([1, 2, 23,23], dtype=th.float)
print(f"max {th.max(tensor_1)}, min {th.min(tensor_1)}")

max 23.0, min 1.0


In [ ]:
# Mean of tensor
print(f"Mean {th.mean(tensor_1)}")

Mean 12.25


##Argmin and Argmax

In [ ]:
tensor_1.argmin(), tensor_1.argmax()

(tensor(0), tensor(2))

## Tensor shape manipulations
1. Reshaping
2. View
3. Permute
4. Stacking

In [ ]:
## Reshaping the tensor
tensor_1 = th.tensor([1, 2, 3, 4])
print(tensor_1.shape)
tensor_changed = tensor_1.reshape(4, 1)
# The reshape should be compatible with the original shape
tensor_changed.shape, tensor_changed

torch.Size([4])


(torch.Size([4, 1]),
 tensor([[1],
         [2],
         [3],
         [4]]))

In [ ]:
##Another example
tensor_range = th.arange(start = 1, end = 101)
print(tensor_range, tensor_range.shape)
tensor_changed = tensor_range.reshape(100, 1)
tensor_changed, tensor_changed.shape

In [ ]:
# Using the view
# Using the view, the new tensor shares the same memory as the previos tensor
tensor_copy = tensor_1.view(4)
tensor_copy

tensor([1, 2, 3, 4])

In [ ]:
# Stacking tensors on top of each other
tensors_stacked = th.stack([tensor_1, tensor_1], dim=1)
tensors_stacked, tensors_stacked.shape

(tensor([[1, 1],
         [2, 2],
         [3, 3],
         [4, 4]]),
 torch.Size([4, 2]))

In [ ]:
# th.stack([list of tensors], dim = 1/0)
# 1 stacks horizontally, and 0 vertically

In [ ]:
x = th.tensor([[1, 1],
               [1, 1]])
print(x, x.shape)
x_stacked = th.hstack([x, x])
x_stacked, x_stacked.shape

tensor([[1, 1],
        [1, 1]]) torch.Size([2, 2])


(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1]]),
 torch.Size([2, 4]))

In [ ]:
## Permute
x = th.tensor([[2, 2],
               [2, 2],
               [23,2]])
print(f"shape of x {x.shape} \n")
y = th.permute(x, (1, 0))
print(f'x size after permute {y.shape}')

shape of x torch.Size([3, 2]) 

x size after permute torch.Size([2, 3])


##Pytorch And Numpy
We can create tensors from numpy arrays and vice versa


In [ ]:
#Numpy array to tensor
array = np.arange(1, 10)
tensor = th.from_numpy(array).type(th.float32)
print(f"Numpy array {array} \n tensor {tensor}")

print(f'Numpy array dtype = {array.dtype} tensor dtype = {tensor.dtype}')



Numpy array [1 2 3 4 5 6 7 8 9] 
 tensor tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Numpy array dtype = int64 tensor dtype = torch.float32


In [ ]:
#Tensor to numpy
tensor = th.ones(9)
numpy_tensor = tensor.numpy()
numpy_tensor.dtype, tensor.dtype, numpy_tensor


(dtype('float32'),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibilty
Making flavoured randomness, using a random seed
Define the random seed and set it
using `th.manual_seed(seed_val)`

In [ ]:
RANDOM_SEED = 42
th.manual_seed(RANDOM_SEED)

random_tensor_A = th.rand(3 , 3)

th.manual_seed(RANDOM_SEED)
random_tensor_B = th.rand(3, 3)

print(random_tensor_A == random_tensor_B)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Setting up GPU
1. Using free colab gpu

In [ ]:
# Device agnostic code
th.cuda.is_available() # False, because we dont have cuda integrated


False

In [ ]:
## If available
device = 'cuda' if th.cuda.is_available() else 'cpu'
device

'cpu'